{
 "title": "Energy monitor",
 "tags": [
  "environment",
  "IoT"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "kwh_price",
    "label": "Electricity price per 1 KWh (Eur)",
    "query": "0.28"
   }
  ]
 },
 "panels": [
  {
   "title": "Latest Data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Power",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "fields": [
      { "jsonPath": "$.W", "name": "", "type": "number" }
     ],
     "method": "GET",
     "params": [
      [
       "",
       ""
      ]
     ]
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "fields": [
      { "jsonPath": "$.totV", "name": "", "type": "number" }
     ],
     "method": "GET"
    }
   ]
  },
  {
   "title": "Current CT1",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "fields": [
      { "jsonPath": "$.CT1", "name": "", "type": "number" }
     ],
     "method": "GET"
    }
   ]
  },
  {
   "title": "Power Factor",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "fields": [
      { "jsonPath": "$.PF", "name": "", "type": "number" }
     ],
     "method": "GET"
    }
   ]
  },
  {
   "title": "Frequency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "fields": [
      { "jsonPath": "$.freq", "name": "", "type": "number" }
     ],
     "method": "GET"
    }
   ]
  },
  {
   "title": "emonESP Satus",
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "targets": [
    {
     "fields": [
      { "jsonPath": "$.ipaddress", "language": "jsonpath", "name": "IP", "type": "string" },
      { "jsonPath": "$.mqtt_connected", "language": "jsonpath", "name": "MQTT", "type": "boolean" }
     ],
     "method": "GET"
    }
   ]
  },
  {
   "title": "Current CT2",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "fields": [
      { "jsonPath": "$.CT2", "name": "", "type": "number" }
     ],
     "method": "GET"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "fields": [
      { "jsonPath": "$.temp", "name": "", "type": "number" }
     ],
     "method": "GET"
    }
   ]
  },
  {
   "title": "Historical Data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Power",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "W{instance=\"mqtt2prometheus:9641\"}",
     "legendFormat": "Power"
    }
   ]
  },
  {
   "title": "Energy Consumption",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "downsampler": "last",
     "expression": "power",
     "type": "resample",
     "upsampler": "backfilling",
     "window": "1h"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "totV{sensor=\"totV\"}",
     "legendFormat": "Voltage"
    },
    {
     "expr": "freq{sensor=\"freq\"}",
     "legendFormat": "Frequency"
    }
   ]
  },
  {
   "title": "Current",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "expr": "CT1{sensor=\"CT1\"}",
     "legendFormat": "CT1"
    },
    {
     "expr": "CT2{sensor=\"CT2\"}",
     "legendFormat": "CT2"
    },
    {
     "expr": "totI{sensor=\"totI\"}",
     "legendFormat": "Total current"
    }
   ]
  },
  {
   "title": "Total energy consumption",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "downsampler": "sum",
     "expression": "energy",
     "reducer": "sum",
     "settings": { "mode": "dropNN" },
     "type": "reduce",
     "upsampler": "fillna"
    }
   ]
  },
  {
   "title": "Total Cost",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "($total_energy/1000)*$kwh_price",
     "type": "math"
    }
   ]
  },
  { "title": "Energy Consumption by Month", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Current Month",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "downsampler": "sum",
     "expression": "energy",
     "reducer": "sum",
     "settings": { "mode": "dropNN" },
     "type": "reduce",
     "upsampler": "fillna"
    }
   ]
  },
  {
   "title": "-1M",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "downsampler": "sum",
     "expression": "energy",
     "reducer": "sum",
     "settings": { "mode": "dropNN" },
     "type": "reduce",
     "upsampler": "fillna"
    }
   ]
  },
  {
   "title": "-2M",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "downsampler": "sum",
     "expression": "energy",
     "reducer": "sum",
     "settings": { "mode": "dropNN" },
     "type": "reduce",
     "upsampler": "fillna"
    }
   ]
  },
  {
   "title": "-3M",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "downsampler": "sum",
     "expression": "energy",
     "reducer": "sum",
     "settings": { "mode": "dropNN" },
     "type": "reduce",
     "upsampler": "fillna"
    }
   ]
  },
  {
   "title": "-4M",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "downsampler": "sum",
     "expression": "energy",
     "reducer": "sum",
     "settings": { "mode": "dropNN" },
     "type": "reduce",
     "upsampler": "fillna"
    }
   ]
  },
  {
   "title": "-5M",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "downsampler": "sum",
     "expression": "energy",
     "reducer": "sum",
     "settings": { "mode": "dropNN" },
     "type": "reduce",
     "upsampler": "fillna"
    }
   ]
  }
 ]
}