{
 "title": "Speedtest",
 "tags": [ "network" ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5m",
 "panels": [
  { "title": "Latest Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Download",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "speedtest_download_bits_per_second{}"
    }
   ]
  },
  {
   "title": "Upload",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "speedtest_upload_bits_per_second{}"
    }
   ]
  },
  {
   "title": "Ping",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "speedtest_ping_latency_milliseconds"
    }
   ]
  },
  {
   "title": "Jitter",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "speedtest_jitter_latency_milliseconds"
    }
   ]
  },
  { "title": "History Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Speedtest Graph",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "speedtest_download_bits_per_second{}",
     "legendFormat": "Download"
    },
    {
     "expr": "speedtest_upload_bits_per_second{}",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "Jitter",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "speedtest_ping_latency_milliseconds",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Jitter",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "speedtest_jitter_latency_milliseconds{}\n",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}